spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/consultorio_odontologico?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.application.name=app_consul
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8080
